# shellcheck shell=bash
# Kit rendering: turn the kit's harness-neutral sources into what each harness
# reads. Sourced by provisioning and tests; compatible with macOS bash 3.2.
#
# Subagents are written once as kit/agents/<name>.md (frontmatter: name,
# description; body: instructions) and rendered to:
#   .claude/agents/<name>.md     Claude Code (frontmatter + body)
#   .codex/agents/<name>.toml    Codex (name, description, developer_instructions)

# Print one frontmatter field of a Markdown file (single-line values only).
kit_frontmatter_get() {  # <file> <key>
  awk -v key="$2" '
    NR == 1 && $0 != "---" { exit }
    NR > 1 && $0 == "---" { exit }
    NR > 1 {
      i = index($0, ":")
      if (i > 0 && substr($0, 1, i - 1) == key) {
        v = substr($0, i + 1); sub(/^[ \t]+/, "", v); sub(/[ \t]+$/, "", v)
        print v; exit
      }
    }
  ' "$1"
}

# Print the body: everything after the closing frontmatter line, with leading
# blank lines removed.
kit_body() {  # <file>
  awk '
    NR == 1 && $0 == "---" { fm = 1; next }
    fm && $0 == "---" { fm = 0; started = 0; next }
    fm { next }
    !started && /^[ \t]*$/ { next }
    { started = 1; print }
  ' "$1"
}

_toml_basic_string() {  # escape for a TOML basic string
  printf '"%s"' "$(printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')"
}

# Render one subagent source into both harness formats under <dest-root>.
kit_render_agent() {  # <source.md> <dest-root>
  local src=$1 dest=$2 name desc body
  name=$(kit_frontmatter_get "$src" name)
  desc=$(kit_frontmatter_get "$src" description)
  case "$name" in
    "" | *[!a-z0-9-]*) echo "kit: $src: name must be lowercase letters, digits and '-'" >&2; return 1 ;;
  esac
  [ "$(basename "$src" .md)" = "$name" ] || { echo "kit: $src: file name must match name '$name'" >&2; return 1; }
  [ -n "$desc" ] || { echo "kit: $src: description is required" >&2; return 1; }
  body=$(kit_body "$src")
  [ -n "$body" ] || { echo "kit: $src: body is empty" >&2; return 1; }
  case "$body" in
    *"'''"*) echo "kit: $src: body may not contain ''' (TOML literal string delimiter)" >&2; return 1 ;;
  esac

  mkdir -p "$dest/.claude/agents" "$dest/.codex/agents"
  {
    printf -- '---\nname: %s\ndescription: %s\n---\n\n' "$name" "$desc"
    printf '<!-- Generated by ai-proj-arch from kit/agents/%s.md. Edit the source, not this file. -->\n\n' "$name"
    printf '%s\n' "$body"
  } > "$dest/.claude/agents/$name.md"
  {
    printf '# Generated by ai-proj-arch from kit/agents/%s.md. Edit the source, not this file.\n' "$name"
    printf 'name = %s\n' "$(_toml_basic_string "$name")"
    printf 'description = %s\n' "$(_toml_basic_string "$desc")"
    printf "developer_instructions = '''\n%s\n'''\n" "$body"
  } > "$dest/.codex/agents/$name.toml"
}

kit_render_agents() {  # <source-dir> <dest-root>
  local f
  for f in "$1"/*.md; do
    [ -e "$f" ] || continue
    kit_render_agent "$f" "$2" || return 1
  done
}

# ------------------------------------------------------------------ install
# Copy the kit into a project checkout and wire it up for both harnesses.
# This is the file-level core that provisioning (#3) wraps with its manifest,
# update PRs and prompts for locally edited files. Overwrites kit-owned files.

KIT_AGENTS_BEGIN='<!-- aipa:begin kit -->'
KIT_AGENTS_END='<!-- aipa:end kit -->'

# Insert or replace the kit block in AGENTS.md, leaving the rest untouched.
kit_merge_agents_md() {  # <kit-block-file> <agents.md>
  local block=$1 target=$2 tmp
  tmp=$(mktemp)
  if [ -f "$target" ] && grep -qF "$KIT_AGENTS_BEGIN" "$target"; then
    grep -qF "$KIT_AGENTS_END" "$target" || { rm -f "$tmp"; echo "kit: $target has a kit begin marker but no end marker" >&2; return 1; }
    awk -v b="$KIT_AGENTS_BEGIN" -v e="$KIT_AGENTS_END" -v f="$block" '
      $0 == b { print; while ((getline l < f) > 0) print l; skip = 1; next }
      $0 == e { skip = 0 }
      !skip { print }
    ' "$target" > "$tmp"
  else
    {
      if [ -f "$target" ]; then cat "$target"; printf '\n'; else printf '# AGENTS.md\n\n'; fi
      printf '%s\n' "$KIT_AGENTS_BEGIN"
      cat "$block"
      printf '%s\n' "$KIT_AGENTS_END"
    } > "$tmp"
  fi
  mv "$tmp" "$target"
}

kit_install() {  # <kit-dir> <repo-dir>
  local kit=$1 repo=$2
  [ -d "$repo/.git" ] || { echo "kit: $repo is not a git checkout" >&2; return 1; }
  mkdir -p "$repo/.agents" "$repo/.github/ISSUE_TEMPLATE" "$repo/.claude"
  # COPYFILE_DISABLE keeps macOS metadata out of copies.
  COPYFILE_DISABLE=1 cp -R "$kit/.agents/." "$repo/.agents/"
  chmod 755 "$repo"/.agents/scripts/*.sh
  cp "$kit"/.github/ISSUE_TEMPLATE/*.md "$repo/.github/ISSUE_TEMPLATE/"
  cp "$kit/.github/pull_request_template.md" "$repo/.github/"

  if [ -L "$repo/.claude/skills" ]; then
    :
  elif [ -e "$repo/.claude/skills" ]; then
    echo "kit: $repo/.claude/skills exists and is not a symlink; move its skills into .agents/skills" >&2
    return 1
  else
    ln -s ../.agents/skills "$repo/.claude/skills"
  fi

  kit_render_agents "$kit/agents" "$repo" || return 1
  kit_merge_agents_md "$kit/AGENTS.kit.md" "$repo/AGENTS.md" || return 1
  if [ ! -f "$repo/CLAUDE.md" ]; then
    cp "$kit/CLAUDE.md" "$repo/CLAUDE.md"
  elif ! grep -qx '@AGENTS.md' "$repo/CLAUDE.md"; then
    printf '\n@AGENTS.md\n' >> "$repo/CLAUDE.md"
  fi
}
